Online_Store/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using AutoMapper;
using Common.Models.DTO;
using Common.Contracts.Services;
using Logic.Services;
using Online_Store.Models;
using Online_Store.Controllers.Base;
using Common.Models.Entities.Identity;
using Microsoft.AspNetCore.Identity;
using Common.Contracts.Services.Identity;
using Online_Store.Areas.Identity.Models;
using System.Security.Claims;

namespace Online_Store.Controllers
{
    public class ProductController:BaseController
    {
        private readonly UserManager<User> _userManager;
        public ProductController(IMapper mapper, IServiceProvider serviceProvider, UserManager<User> userManager)
            : base(mapper, serviceProvider)
        {
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            ShoppingCartDto cartDTO;
            var user = await _userManager.GetUserAsync(HttpContext.User);
            
            if(user != null)
                cartDTO = _serviceProvider.GetRequiredService<IShoppingCartService>().GetCartByUser(user.Id);
            else
                cartDTO = new ShoppingCartDto { ShoppingCartItems = new List<ShoppingCartItemDto>()};

            var cartVM = _mapper.Map<ShoppingCartViewModel>(cartDTO);

            var categoriesDTO = _serviceProvider.GetRequiredService<ICategoryService>().GetCategories();

            if (categoriesDTO == null)
                return BadRequest();

            cartVM.Categories = _mapper.Map<List<CategoryIndexViewModel>>(categoriesDTO);
            cartVM.CategoryId = cartVM.Categories[0].Id;
            return View(cartVM);
        }

        public PartialViewResult GetProducts(CartTableViewModel cart)
        {
            var productsDTO = _serviceProvider
                .GetRequiredService<IProductService>()
                .GetProductsByCategory(cart.CategoryId);

            cart.Products = _mapper.Map<List<ProductCustomerViewModel>>(productsDTO);

            return PartialView("Partials/_CategorySelectPartial", cart);
        }

        public PartialViewResult GetCartItems(ShoppingCartViewModel cart)
        {
            var items = _serviceProvider.GetRequiredService<IShoppingCartItemService>().GetItems(cart.Id);
            cart.ShoppingCartItems = _mapper.Map<List<ShoppingCartItemViewModel>>(items);
            return PartialView("Partials/_CartPartial", cart);
        }



        [HttpGet]
        public IActionResult Details(Guid id)
        {
            ProductDto product = _serviceProvider.GetRequiredService<IProductService>().GetProduct(id);
            ProductCustomerViewModel productVM = _mapper.Map<ProductCustomerViewModel>(product);

            return View(productVM);
        }
    }
}

Online_Store/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using AutoMapper;
using Common.Models.DTO;
using Common.Contracts.Services;
using Logic.Services;
using Online_Store.Models;
using Online_Store.Controllers.Base;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting;
using System.Web;


namespace Online_Store.Controllers
{
    public class ShoppingCartController:BaseController
    {
        public ShoppingCartController(IMapper mapper, IServiceProvider serviceProvider)
            : base(mapper, serviceProvider)
        {

        }

        public IActionResult Index(Guid cartid)
        {
            var cartDTO = _serviceProvider.GetRequiredService<IShoppingCartService>().GetCart(cartid);

            if (cartDTO == null)
                return BadRequest();

            var cartVM = _mapper.Map<ShoppingCartViewModel>(cartDTO);

            return View(cartVM);
        }

        [HttpPost]
        public JsonResult Add(Guid CartId, Guid ProductId, int amount)
        {
            if (CartId == default)
                return Json(new
                {
                    Data = new
                    {
                        isValid = false
                    }
                });

            bool isValidAmount = false;

            var product = _serviceProvider.GetRequiredService<IProductService>().GetProduct(ProductId);

            if (product != null && amount <= product.Quantity)
            {
                var item = new ShoppingCartItemDto { Product = product, Id = Guid.NewGuid(), ShoppingCartId = CartId, Amount = amount };
                isValidAmount = _serviceProvider.GetRequiredService<IShoppingCartService>().AddToCart(item);
            }

            return Json(new
            {
                Data = new
                {
                    isValid = isValidAmount
                }
            });
        }

        [HttpPost]
        public JsonResult Remove(Guid ItemId)
        {
            _serviceProvider.GetRequiredService<IShoppingCartItemService>().DeleteItem(ItemId);
            return Json(new
            {
                Data = new
                {
                    //isValid = isValidAmount
                }
            });
        }
    }
}

Online_Store/Views/Shared/_EntryPartial.cshtml
<div align="right">
    @if (User.Identity.IsAuthenticated)
    {
        <form method="post" asp-area="" asp-controller="Account" asp-action="Logout">
            <input class="btn btn-info" type="submit" value="Выход" />
        </form>
    }
    else
    {
        <a class="btn btn-info" asp-controller="Account" asp-action="Authorize">Вход</a>
        <br />
        <a  class="btn btn-info" asp-controller="Account" asp-action="Register">Регистрация</a>
    }
</div>

Online_Store/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Online_Store</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/SideBar.css" />
    <link rel="stylesheet" href="~/css/Cart.css" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <base href="/">
    <style>
        input::-webkit-outer-spin-button,
        input::-webkit-inner-spin-button {
            -webkit-appearance: none;
            margin: 0;
        }
        input[type=number] {
            -moz-appearance: textfield;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-dark bg-primary">
            <a class="navbar-brand" asp-controller="Product" asp-action="Index">Онлайн магазин</a>
            <partial name="_EntryPartial" />
        </nav>
    </header>

    <div class='sidebar'>
        <ul>
            <li>Item 1</li>
            <li>Item 2</li>
        </ul>
    </div>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.js"></script>
    <script>
        $(document).ready(function () {
            $('#table_id').DataTable();
        });

        $('#check').change(function (element) {
            var id = element.target.value
            var cartid = element.target.attributes["data-cart-id"].nodeValue;
            UpdateProducts(id, cartid);
        });



    </script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <partial name="_Urls" />
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Online_Store/Views/Shared/_Urls.cshtml
<script>
    var urls = {
        AddItemToCart: "@Url.Action("Add", "ShoppingCart")",
        RemoveItemFromCart: "@Url.Action("Remove", "ShoppingCart")",
        GetCartItems: "@Url.Action("GetCartItems", "Product")",
        GetProducts: "@Url.Action("GetProducts", "Product")"
    };
</script>